### PR TITLE
A11y Fix in Success view State

### PR DESCRIPTION
**Pull request by jwalakom**

### CODE REVIEW

**Review by arnimma — COMMENTED** [review]
make it consistent with all type of state views

**Review by arnimma — APPROVED** [review]

**Comment by jwalakom** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by jwalakom** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by jwalakom** [comment]
@microsoft-github-policy-service agree

**Comment by jwalakom** [comment]
@microsoft-github-policy-service agree

**Comment by jwalakom** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by oubaib — APPROVED** [review]

**Pull request merged**
